# Generated by Django 6.0.4 on 2026-05-10 06:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carouselsection_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Photo/documentation/image', verbose_name='Фото документации')),
                ('name', models.CharField(max_length=100, verbose_name='Название документа')),
                ('pdf_file', models.FileField(upload_to='Photo/documentation/pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документация',
            },
        ),
        migrations.CreateModel(
            name='TableCatalog2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Photo/catalog/cards', verbose_name='Изображение товара')),
                ('name', models.CharField(max_length=100, verbose_name='Продукция')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('measurement', models.CharField(max_length=100, verbose_name='Измерение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за ед.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Таблица для каталога(2)',
                'verbose_name_plural': 'Таблицы для каталога(2)',
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Таблица для каталога(1)', 'verbose_name_plural': 'Таблицы для каталога(1)'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Объем от скидки (м³)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Длина (м)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_per_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за м³'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sheets_per_pack',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество листов в упаковке (шт)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='surface',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип поверхности'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Толщина (мм)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ширина (мм)'),
        ),
        migrations.CreateModel(
            name='PlywoodCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Photo/catalog/plywood', verbose_name='Изображение товара')),
                ('name', models.CharField(max_length=100, verbose_name='Продукция')),
                ('thickness', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Толщина (мм)')),
                ('sheets_per_pack', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество листов в упаковке (шт)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.grade', verbose_name='Сорт')),
                ('surface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.surface', verbose_name='Тип поверхности')),
            ],
            options={
                'verbose_name': 'Таблица для каталога(3)',
                'verbose_name_plural': 'Таблицы для каталога(3)',
            },
        ),
    ]
