# Generated by Django 6.0.4 on 2026-05-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_documentation_tablecatalog2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+7 (888) 888-88-88', max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(default='adress_email.ru', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='г. Томск, ул. Кузовлевский тракт, 2Б ст31', max_length=255, verbose_name='Адрес')),
                ('work_hours', models.CharField(default='Пн-Пт: 9:00-18:00, Сб: 10:00-16:00', max_length=255, verbose_name='Режим работы')),
                ('footer_text', models.CharField(default='© 2026 ООО «СДК». Все права защищены.', max_length=255, verbose_name='Текст в футере')),
                ('contact_text', models.TextField(default='Нужна консультация? Оставьте свой номер — мы перезвоним и ответим на все вопросы.', verbose_name='Текст в блоке консультации')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
